# ==============================================================================
# KillerWhale — Alacritty Terminal Configuration
# Estética: Terminal Fósforo Verde CRT / Minimalista
# ==============================================================================

[window]
padding = { x = 6, y = 6 }
dynamic_padding = true
opacity = 0.98
decorations = "none"
startup_mode = "Fullscreen"

[font]
size = 11.0

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[colors.primary]
background = "#000000"
foreground = "#00ffd1"

[colors.cursor]
text = "#000000"
cursor = "#4dffef"

[colors.selection]
text = "#000000"
background = "#00ffd1"

[colors.normal]
black   = "#000000"
red     = "#ff3355"
green   = "#00ffd1"
yellow  = "#00b398"
blue    = "#0088ff"
magenta = "#b800e6"
cyan    = "#4dffef"
white   = "#e6ffff"

[colors.bright]
black   = "#002620"
red     = "#ff5577"
green   = "#4dffef"
yellow  = "#00ffd1"
blue    = "#33a3ff"
magenta = "#cc33ff"
cyan    = "#4dffef"
white   = "#ffffff"

