# ==============================================================================
# KillerWhale — Kitty Terminal Configuration
# Estética: Terminal Fósforo Verde CRT / Minimalista
# ==============================================================================

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

background_opacity 0.98
window_padding_width 6
hide_window_decorations yes
confirm_os_window_close 0

# Paleta Central KillerWhale
foreground #00ffd1
background #000000
cursor     #4dffef
cursor_text_color #000000

selection_foreground #000000
selection_background #00ffd1

# Cores Padrão
color0 #000000
color1 #ff3355
color2 #00ffd1
color3 #00b398
color4 #0088ff
color5 #b800e6
color6 #4dffef
color7 #e6ffff

# Cores Brilhantes
color8  #002620
color9  #ff5577
color10 #4dffef
color11 #00ffd1
color12 #33a3ff
color13 #cc33ff
color14 #4dffef
color15 #ffffff
