# ==============================================================================
# KillerWhale — Kitty Terminal Configuration
# Estética: Terminal Fósforo Verde CRT / Minimalista
# ==============================================================================

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

background_opacity 0.98
window_padding_width 6
hide_window_decorations yes
confirm_os_window_close 0

# Paleta Central KillerWhale
foreground #00ff66
background #050a05
cursor     #66ff99
cursor_text_color #050a05

selection_foreground #050a05
selection_background #00ff66

# Cores Padrão
color0 #050a05
color1 #ff3333
color2 #00cc52
color3 #ffb000
color4 #0088ff
color5 #b800e6
color6 #00e5cc
color7 #e0f2e0

# Cores Brilhantes
color8  #1f3a1f
color9  #ff5555
color10 #00ff66
color11 #ffd24d
color12 #33a3ff
color13 #cc33ff
color14 #33ffee
color15 #ffffff
